version: '3.3'
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=biblioteca
  app:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
